# Generated by Django 5.2.8 on 2025-12-10 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_equipo_actualizado_en_equipo_creado_en_equipo_estado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='creado_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
