# Generated by Django 5.2.8 on 2025-12-10 04:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_alter_equipo_creado_en'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='creado_en',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 12, 10, 4, 37, 21, 288072, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
